name: Publish to PyPI

on:

  # .. note: There can be many tags, which can be created directly
  #          from the terminal. However, not all tags are completed
  #          with a release. Note that when creating a release, for
  #          example using the github interface, it has a tag
  #          associated.

  workflow_run:
    workflow: ['Python package']
    types: [completed]
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Build distribution
        run: |
          python -m pip install build
          #python setup.py sdist bdist_wheel # old (setup.cfg)
          python -m build --sdist --wheel    # new (pyproject.toml)

      - name: Publish package on TestPyPI
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          pip install setuptools wheel twine
          twine upload -r testpypi dist/*
